name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_testing:
    strategy:
      matrix:
        node-version: [16, 18, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint:prettier
      - run: pnpm run lint:eslint

  unit_testing:
    strategy:
      matrix:
        node-version: [16, 18, 20]
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres
      JWT_SECRET: fjk/OkW5L+yYMrXryt0RPqUX+0YfTOxcjedyB30x8NI=
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      BASE_URL: http://localhost:3000
    services:
      postgres:
        image: postgres:16.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 127.0.0.1:5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm exec prisma migrate deploy
      - run: pnpm run test
      - uses: MishaKav/jest-coverage-comment@v1.0.25
        if: false

  e2e_testing:
    strategy:
      matrix:
        node-version: [16, 18, 20]
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres
      JWT_SECRET: fjk/OkW5L+yYMrXryt0RPqUX+0YfTOxcjedyB30x8NI=
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      BASE_URL: http://localhost:3000
    services:
      postgres:
        image: postgres:16.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 127.0.0.1:5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm exec prisma migrate deploy
      - run: pnpm run test:e2e
